### ISSUE TITLE
Disabling CHIPoBLE service due to error: Error ESP32:0x05B00103

### ISSUE THREAD

**Issue by darrenlock** [jakubdybczak/esp32-arduino-matter#13]
The Light example was all working a couple weeks ago and I was able to add the device to SmartThings OK. I re-uploaded the image again today and now I cannot get the Device to provision. Is the following error about not being able to start BLE a red herring?:
I (4061) chip[DL]: NVS set: chip-counters/total-hours = 0 (0x0)
I (4062) chip[DL]: NVS set: chip-config/unique-id = "B659D4A2066D2F82"
I (4064) chip[DL]: Changing ESP WiFi mode: AP -> STA+AP
I (4070) chip[DL]: Changing ESP WiFi mode: STA+AP -> STA
I (4076) chip[DL]: Real time clock set to 946684800 (0100/00/01 00:00:00 UTC)
D (8501) chip[DL]: CHIP task running
E (8505) chip[DL]: Disabling CHIPoBLE service due to error: Error ESP32:0x05B00103
I (8512) chip[DL]: Starting ESP WiFi layer
I (8666) chip[DL]: Done driving station state, nothing else to do...
E (8666) chip[DL]: Long dispatch time: 154 ms, for event type 3
I (8667) chip[DL]: Done driving station state, nothing else to do...
I (8673) chip[SVR]: Server initializing...
D (8676) chip[FP]: Initializing FabricTable from persistent storage

The ESP get all the way to awaiting pairing but never responds to a pairing request:
I (9012) chip[DL]: WIFI_EVENT_STA_START
E (9009) esp_matter_core: Failed to open the node nvs_namespace
I (9016) chip[DL]: Done driving station state, nothing else to do...
I (9026) chip[SVR]: SetupQRCode: [MT:Y.K9042C00KA0648G00]
I (9033) chip[SVR]: Copy/paste the below URL in a browser to see the QR Code:
I (9039) chip[SVR]: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3AY.K9042C00KA0648G00
I (9049) chip[SVR]: Manual pairing code: [34970112332]

I've made sure the Flash is erased on upload but this has not had any noticeable effect.
I'm wondering if something in my Dev Environment has changed? I've tried a clean rebuild.

**Comment by jakubdybczak** [comment]
`due to error: Error ESP32:0x05B00103` means that error is created within ESP32 API and it's `ESP_ERR_INVALID_STATE` ([source](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/error-codes.html)) which unfortunately can mean lots of things. I encoured same error when Arduino stack was trying to release BLE memory (it's done for memory optimization, when you don't use any Bluetooth stuff from arduino-esp32 repo), so I tricked arduino-esp32 into thinking that it's using bluetooth here: https://github.com/jakubdybczak/esp32-arduino-matter/blob/master/src/Matter.h. But I guess in your case problem is caused by different thing. Could you post your:
- ESP32 model
- Arduino version (version of board)
- Sample sketch that causes this error

This will help with further investigation

**Comment by darrenlock** [comment]
Apologies for delay in replying, I have been away this week. I completely deleted the Matter library from my Arduino folder and re-added from ZIP. Recompiled and now works again. Something in the environment must have got messed up?
